[Variables]
fontName=Trebuchet MS
textSize=12
colorBar=235,170,0,255
colorText=255,255,255,205
colorTextDim=255,255,255,115
colorTextLB=150,150,255,255

[styleTitle]
StringAlign=Left
StringCase=Upper
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=14
AntiAlias=1
ClipString=1

[styleOLB]
StringAlign=Right
StringCase=Upper
; StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorTextLB#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleGameName]
StringAlign=Left
; Meters using styleLeftText will be left-aligned.
StringCase=None
; StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,220
FontColor=#colorText#
FontFace=#fontName#
FontSize=12
AntiAlias=1
ClipString=1

[styleGamePlayCount]
StringAlign=Right
StringCase=None
; StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorTextLB#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

