[meterGameBox0]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "0"]
shape = Rectangle (#offsetX# + #entryW# * 0 + #spacingW# * 0),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt0]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 0
updatedivider = 1

[meterGameArt0]
meter = Image
measurename = measureGameArt0
imagename = [measureGameArt0]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 0 + #spacingW# * 0 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName0]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 0
updatedivider = 1

[meterGameName0]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName0
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 0 + #spacingW# * 0 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[meterGameBox1]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "1"]
shape = Rectangle (#offsetX# + #entryW# * 1 + #spacingW# * 1),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt1]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 1
updatedivider = 1

[meterGameArt1]
meter = Image
measurename = measureGameArt1
imagename = [measureGameArt1]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 1 + #spacingW# * 1 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName1]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 1
updatedivider = 1

[meterGameName1]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName1
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 1 + #spacingW# * 1 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[meterGameBox2]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "2"]
shape = Rectangle (#offsetX# + #entryW# * 2 + #spacingW# * 2),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt2]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 2
updatedivider = 1

[meterGameArt2]
meter = Image
measurename = measureGameArt2
imagename = [measureGameArt2]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 2 + #spacingW# * 2 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName2]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 2
updatedivider = 1

[meterGameName2]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName2
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 2 + #spacingW# * 2 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[meterGameBox3]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "3"]
shape = Rectangle (#offsetX# + #entryW# * 3 + #spacingW# * 3),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt3]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 3
updatedivider = 1

[meterGameArt3]
meter = Image
measurename = measureGameArt3
imagename = [measureGameArt3]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 3 + #spacingW# * 3 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName3]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 3
updatedivider = 1

[meterGameName3]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName3
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 3 + #spacingW# * 3 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[meterGameBox4]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "4"]
shape = Rectangle (#offsetX# + #entryW# * 4 + #spacingW# * 4),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt4]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 4
updatedivider = 1

[meterGameArt4]
meter = Image
measurename = measureGameArt4
imagename = [measureGameArt4]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 4 + #spacingW# * 4 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName4]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 4
updatedivider = 1

[meterGameName4]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName4
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 4 + #spacingW# * 4 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[meterGameBox5]
meter = Shape
leftmouseupaction = [!CommandMeasure "#onClickMeasure#" "5"]
shape = Rectangle (#offsetX# + #entryW# * 5 + #spacingW# * 5),(#offsetY# + #textCoverH#),#entryW#,(#entryH# - #textCoverH#) | Fill Color 0,0,0,255 | StrokeWidth 2 | Stroke Color 255,255,255,50

[measureGameArt5]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesArtMeasure()
recententry = 5
updatedivider = 1

[meterGameArt5]
meter = Image
measurename = measureGameArt5
imagename = [measureGameArt5]
w = #gameImageW#
h = #gameImageH#
x = (#offsetX# + #entryW# * 5 + #spacingW# * 5 + #gameImageX#)
y = (#offsetY# + #gameImageY#)

[measureGameName5]
measure = Plugin
plugin = PyPlugin
info = #@#py/mod_info.json
loader = RecentGamesNameMeasure()
recententry = 5
updatedivider = 1

[meterGameName5]
meter = String
meterstyle = #GameNameStyle#
measurename = measureGameName5
w = #gameNameW#
h = #gameNameH#
x = (#offsetX# + #entryW# * 5 + #spacingW# * 5 + #gameNameX#)
y = (#offsetY# + #gameNameY#)

[Variables]
totalw = (#offsetX# + #entryW# * 6 + #spacingW# * 6)
totalh = (#offsetY# + #entryH# + #spacingH#)

